name: "transcribo"

services:
  transcriber:
    image: transcribo:aargau
    container_name: transcribo
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - hugging_face_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]

volumes:
  hugging_face_cache:
